---
# tasks file for ansible_galaxy_role_ubuntu-update-upgrade
- name: "update, upgrade, autoremove Ubuntu | update packages"
  become: yes
  apt:
    name: '*'
    state: latest

- name: "update, upgrade, autoremove Ubuntu | upgrade packages"
  become: yes
  apt:
    upgrade: dist

- name: "update, upgrade, autoremove Ubuntu | autoremove packages"
  become: yes
  apt:
    autoremove: yes